import Head from "next/head";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import ModelY from "../components/ModelY";
import ModelS from "../components/ModelS";
import ModelX from "../components/ModelX";
import SolarPanels from "../components/SolarPanels";
import SolarRoof from "../components/SolarRoof";
import Accessories from "../components/Accessories";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header />
      <ModelY />
      <ModelS />
      <ModelX />
      <SolarPanels />
      <SolarRoof />
      <Accessories />
    </>
  );
}
